dateModified: 1777020136
email:
  fromEmail: g.woodman@outlook.com
  fromName: 'George Woodman Dev'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  localPrivate:
    hasUrls: false
    name: 'Local (Private)'
    settings:
      path: '@storage/uploads'
    type: craft\fs\Local
    url: null
  localWebRoot:
    hasUrls: true
    name: 'Local (Web Root)'
    settings:
      path: '@webroot/uploads'
    type: craft\fs\Local
    url: $FILESYSTEM_URL_PUBLIC
meta:
  __names__:
    1ad1f6f8-f49a-4bb7-9e8c-35f3fc6ee2dc: 'Meta Title' # Meta Title
    001e0cd3-39f5-451f-918d-1a6654aee7e5: 'Item Link' # Item Link
    2e9c4b28-924c-4666-ad64-e97f3ab5f785: 'George Woodman Dev' # George Woodman Dev
    2f6a3505-4496-4c17-9fc8-08507bb80d5e: 'Copy & Media' # Copy & Media
    3b23bbea-ddfb-4906-bbe9-a6b1507b53cd: 'Accordion Item' # Accordion Item
    3bdc3b6b-d913-46b2-858b-db459000e0b1: 'Meta Description' # Meta Description
    3d7d5bfe-e425-4524-af66-147426a6fc27: Header # Header
    3e92d383-0dca-40cf-a1e3-8a92860e9565: Button # Button
    3fd58a8a-1242-40a7-8a80-a53126c50fb9: 'Accordion Type' # Accordion Type
    4a3573cb-e2ca-475f-b739-56b2b6559352: 'Navigation Item' # Navigation Item
    4c041fab-6a61-4afa-bbfe-e27d6f5dd4e0: 'Page Builder' # Page Builder
    5e94b30f-0f9d-492b-bc64-13ab6287c92d: 'OG Image' # OG Image
    5ef45de4-aa12-40bb-89b0-ec4b7f9f1677: 'Sub Navigation Item' # Sub Navigation Item
    5fdee11c-9ea3-4de3-8d76-5825bf95222a: 'Modules Pages' # Modules Pages
    7df558db-d939-4096-8a38-33326dc5a62c: 'Show Dropdown' # Show Dropdown
    7e41e6c2-6bd3-41ce-a03f-ec81dd47c5f6: Card # Card
    7e51ac86-75e4-4dde-83de-58ebbb59f1e7: 'Copy Only' # Copy Only
    9dfe14e2-5866-4d7f-92c8-59a6c28aad95: Content # Content
    26cce803-31f3-4c4f-8649-3eb882168a86: 'Homepage Hero' # Homepage Hero
    44c3465f-6c5d-4511-8d6e-def57fde2e8f: 'Column Heading' # Column Heading
    53bbcd4a-9def-4156-9e68-6c7f8019c7fa: Video # Video
    54b6f09b-f012-4030-ac98-3a22a01837a3: Footer # Footer
    79ce91d6-8c83-44be-a95b-198841152295: Default # Default
    89c057ba-4343-4094-8724-f4e1f1084896: 'Media Width' # Media Width
    92cb8c3f-4fe5-4c48-917b-4974b1323de8: Homepage # Homepage
    95f73348-6bb3-48bf-a67a-d84c05fe59ec: Subheading # Subheading
    136a4f9c-e2b3-4174-9979-69cefeb9ceff: 'Column Link' # Column Link
    150eb063-4ed1-4b80-8fb8-148ecfcfa96c: Buttons # Buttons
    326f66a7-577c-412b-9815-5a55b0cfa1d1: Accordion # Accordion
    340eed21-85d5-4461-a176-d11b1ff5b3a6: 'User Photos' # User Photos
    0383bc8a-e637-484e-b87a-0ffd134c8162: 'Introduction Text' # Introduction Text
    513c0726-c6a0-46e6-8ccf-6963b6211909: 'Media Type' # Media Type
    608dee82-9418-4235-a9c0-53a817c2cacc: Image # Image
    661fe038-a9cd-4e88-8a39-d8cf5c238cce: 'Hero Banner' # Hero Banner
    699b5baf-4d31-450d-b6d4-1c5748eec82b: Cards # Cards
    861f9f97-b77f-44f9-a188-b9e67b7394a2: Entry # Entry
    1139fcce-fbf5-411d-a668-130e00b06f48: 'Accordion Title' # Accordion Title
    09466f53-5c43-44b8-877d-70ae8f69c0ed: 'Card Link' # Card Link
    327636c6-2ab4-4877-8208-1315913ce380: 'No Follow' # No Follow
    456077b2-b77b-4f46-b4b8-069436fc88af: 'Full Width Media' # Full Width Media
    10639296-e516-422a-b738-d6027c7fa7df: 'George Woodman Dev' # George Woodman Dev
    a1e70991-90fb-40da-b851-5978947dbb6a: 'Canonical URL' # Canonical URL
    a3630eb9-60dd-45f5-8ccd-17177a582438: 'Column Items' # Column Items
    a71055de-9d4a-40de-9dd1-ff9f478dc461: 'Button Link' # Button Link
    aa68fe4c-1fc8-4dc7-ad17-aa8e75b573eb: 'Sub Navigation' # Sub Navigation
    aa913870-ca6c-42b2-b1f8-05227715acdb: 'No Index' # No Index
    ac1caba1-2592-4da2-ae3a-0da590497fdb: 'Site Assets' # Site Assets
    acbf8090-87b9-483e-9f42-26a54f5d8072: 'Text Alignment' # Text Alignment
    af1273d1-2c10-4bee-b314-d9cc42ebba11: 'Card Summary' # Card Summary
    b7e4d86b-b387-4949-afbf-0d2d2a3729ee: Homepage # Homepage
    b553df29-4a23-4a96-b62c-b4a4ef1fa01e: 'Card Type' # Card Type
    ba8d269c-876e-456d-be7b-4ac668a0703b: 'Card Image' # Card Image
    bc90b679-0a99-4882-8aa6-fcdf2bd554e9: Simple # Simple
    bf63dd09-17a7-48ae-b1d0-f950e90d6fb5: Heading # Heading
    bffadb38-aeb0-4db3-b8e3-8cd02f8781a1: 'Header Navigation' # Header Navigation
    c4b6d510-bc29-4c46-b3b2-325b63a6b6af: 'First Item Open' # First Item Open
    c4fba5d5-6480-4b26-b3c2-850a8ef719d7: 'Card Title' # Card Title
    c55ca0a9-4bd6-409b-afd8-c1884dafecd0: Team # Team
    c8188e53-9166-4ef6-87c2-a874cbe8d2b2: 'Button Text' # Button Text
    d8197259-a569-4a9e-a1c0-61a702caaccb: 'Background Image' # Background Image
    e1612f48-2a9d-4807-b648-93613a63047d: 'Accordion Items' # Accordion Items
    eb0ded51-07ad-483e-852f-e504254f7183: 'Allow Multiple Open' # Allow Multiple Open
    efcab269-b144-4f31-a096-f07a071d3f03: 'Media Position' # Media Position
    f3ef969a-f1a6-40ad-99f0-3e207a770b82: 'Sub Navigation Column' # Sub Navigation Column
    f81e639e-60fb-4175-a1e2-1649798a0da4: 'Card CTA Text' # Card CTA Text
    f6615dc1-3895-45c5-88a1-c17a8629a2f4: 'Card Items' # Card Items
    f83396a7-4923-4c2b-96b2-542bbd87154f: 'Modules Page' # Modules Page
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 5.0.0.1
  dashboard-begone:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: team
  live: true
  name: 'George Woodman Dev'
  schemaVersion: 5.9.0.8
  timeZone: America/Los_Angeles
