dateModified: 1778237932
email:
  fromEmail: g.woodman@outlook.com
  fromName: 'George Woodman Dev'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  localPrivate:
    hasUrls: false
    name: 'Local (Private)'
    settings:
      path: '@storage/uploads'
    type: craft\fs\Local
    url: null
  localWebRoot:
    hasUrls: true
    name: 'Local (Web Root)'
    settings:
      path: '@webroot/uploads'
    type: craft\fs\Local
    url: $FILESYSTEM_URL_PUBLIC
meta:
  __names__:
    0f9b9e17-101f-4872-b379-0580759feb60: Heading # Heading
    1ad1f6f8-f49a-4bb7-9e8c-35f3fc6ee2dc: 'Meta Title' # Meta Title
    1cefd0e6-6e15-4ad1-8a08-39bf4b723eda: Caption # Caption
    2e9c4b28-924c-4666-ad64-e97f3ab5f785: 'George Woodman Dev' # George Woodman Dev
    3bdc3b6b-d913-46b2-858b-db459000e0b1: 'Meta Description' # Meta Description
    3d7d5bfe-e425-4524-af66-147426a6fc27: Header # Header
    4c041fab-6a61-4afa-bbfe-e27d6f5dd4e0: 'Page Builder' # Page Builder
    5e94b30f-0f9d-492b-bc64-13ab6287c92d: 'OG Image' # OG Image
    5fdee11c-9ea3-4de3-8d76-5825bf95222a: 'Modules Pages' # Modules Pages
    09ce0edf-8e53-41b3-8bba-638137be0807: 'Body Text' # Body Text
    54b6f09b-f012-4030-ac98-3a22a01837a3: Footer # Footer
    71e33e54-78fb-4f11-b849-99b5049f05c1: Subheading # Subheading
    79ce91d6-8c83-44be-a95b-198841152295: Default # Default
    92cb8c3f-4fe5-4c48-917b-4974b1323de8: Homepage # Homepage
    340eed21-85d5-4461-a176-d11b1ff5b3a6: 'User Photos' # User Photos
    425e0dd8-9efc-496f-aa86-2016bb728814: 'Intro Text' # Intro Text
    327636c6-2ab4-4877-8208-1315913ce380: 'No Follow' # No Follow
    832307e6-5881-4c7f-9c1d-6cea16f9108f: 'Anchor ID' # Anchor ID
    10639296-e516-422a-b738-d6027c7fa7df: 'Lucidity Lab Core' # Lucidity Lab Core
    a1e70991-90fb-40da-b851-5978947dbb6a: 'Canonical URL' # Canonical URL
    aa913870-ca6c-42b2-b1f8-05227715acdb: 'No Index' # No Index
    ac1caba1-2592-4da2-ae3a-0da590497fdb: 'Site Assets' # Site Assets
    b7e4d86b-b387-4949-afbf-0d2d2a3729ee: Homepage # Homepage
    bc90b679-0a99-4882-8aa6-fcdf2bd554e9: Simple # Simple
    c55ca0a9-4bd6-409b-afd8-c1884dafecd0: Team # Team
    f83396a7-4923-4c2b-96b2-542bbd87154f: 'Modules Page' # Modules Page
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 5.0.0.1
  dashboard-begone:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: team
  live: true
  name: 'George Woodman Dev'
  schemaVersion: 5.9.0.8
  timeZone: America/Los_Angeles
