fieldLayouts:
  3611e71e-d7fd-467a-adf0-efaf2ccb2089:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        name: Navigation
        uid: 1eeac5f0-8563-446f-b88a-3bc685f7dc8d
        userCondition: null
    thumbFieldKey: null
handle: header
name: Header
sortOrder: 2
