columnSuffix: null
handle: accordionItems
instructions: null
name: 'Accordion Items'
searchable: false
settings:
  createButtonLabel: 'Add Item'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 3b23bbea-ddfb-4906-bbe9-a6b1507b53cd # Accordion Item
        -
          - group
          - Items
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
