columnSuffix: null
handle: anchorId
instructions: 'A unique ID used for deep linking to this section (e.g. about-us). No spaces or special characters. Leave blank if unsure.'
name: 'Anchor ID'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
