columnSuffix: null
handle: backgroundColour
instructions: 'Sets the background colour of this block. Alternate between colours across consecutive blocks to create visual separation without relying on borders.'
name: 'Background Colour'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - None
        -
          - value
          - none
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Light
        -
          - value
          - light
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Dark
        -
          - value
          - dark
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Primary
        -
          - value
          - primary
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Secondary
        -
          - value
          - secondary
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
