columnSuffix: null
handle: enableCaptcha
instructions: 'Adds an invisible honeypot field and a minimum submission time to filter out automated bots. Recommended for all public forms.'
name: 'Enable Spam Protection'
searchable: false
settings:
  default: true
  offLabel: null
  onLabel: null
  showLabelsInCards: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
