columnSuffix: null
handle: formFieldAllowMultiple
instructions: 'When enabled, the visitor can select more than one option.'
name: 'Allow Multiple Selections'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
  showLabelsInCards: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
