columnSuffix: null
handle: formFieldRows
instructions: 'Visible height of the textarea, in rows.'
name: Rows
searchable: false
settings:
  decimals: 0
  defaultValue: 5
  max: null
  min: 2
  prefix: null
  previewFormat: decimal
  size: null
  step: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
