columnSuffix: null
handle: formFieldOptions
instructions: null
name: Options
searchable: false
settings:
  addRowLabel: 'Add Option'
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - Label
            -
              - handle
              - label
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - Value
            -
              - handle
              - value
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col3
        -
          __assoc__:
            -
              - heading
              - Default
            -
              - handle
              - default
            -
              - width
              - ''
            -
              - type
              - checkbox
  defaults:
    -
      __assoc__:
        -
          - col1
          - ''
        -
          - col2
          - ''
        -
          - col3
          - ''
        -
          - rowId
          - 42dd7fc9-aaf2-48d9-9954-e39724a065b9
  maxRows: null
  minRows: null
  staticRows: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
