columnSuffix: null
handle: form
instructions: 'Select the form to display in this module. Forms are managed under Forms in the sidebar so the same form can be reused across multiple pages.'
name: Form
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  defaultPlacement: end
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  selectionLabel: 'Select Form'
  showCardsInGrid: false
  showSiteMenu: false
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: luciditylab\craftFormBuilder\fields\FormsField
