columnSuffix: null
handle: formFieldMaxFileSize
instructions: 'Largest permitted upload size in megabytes.'
name: 'Maximum File Size'
searchable: false
settings:
  decimals: 0
  defaultValue: 5
  max: null
  min: 1
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  step: null
  suffix: ' MB'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
