columnSuffix: null
handle: formFieldAllowedFileTypes
instructions: null
name: 'Allowed File Types'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: 'pdf, doc, docx'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
