columnSuffix: null
handle: fromAddress
instructions: 'Do not set this to the visitor’s address, use Reply-To for that. Leave blank to use the system default.'
name: 'From Address'
searchable: false
settings:
  placeholder: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Email
