columnSuffix: null
handle: introText
instructions: 'A short introductory paragraph. Plain text only, no formatting.'
name: 'Intro Text'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
