columnSuffix: null
handle: itemDropdown
instructions: null
name: 'Show Dropdown'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
