columnSuffix: null
handle: mediaPosition
instructions: null
name: 'Media Position'
searchable: false
settings:
  default: false
  offLabel: Left
  onLabel: Right
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
