columnSuffix: null
handle: navigation
instructions: null
name: 'Header Navigation'
searchable: false
settings:
  createButtonLabel: 'Add Item'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 4a3573cb-e2ca-475f-b739-56b2b6559352 # Navigation Item
        -
          - group
          - Items
  includeTableView: false
  maxEntries: 10
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
