columnSuffix: null
handle: openFirstItem
instructions: 'When enabled, the first accordion item will be open by default on page load.'
name: 'Open First Item'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
  showLabelsInCards: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
