columnSuffix: null
handle: paddingSize
instructions: 'Controls the vertical spacing above and below the block content. Defaults to Medium. Setting this to None on consecutive blocks may cause them to appear merged.'
name: 'Padding Size'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - None
        -
          - value
          - none
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Small
        -
          - value
          - small
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Medium
        -
          - value
          - medium
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Large
        -
          - value
          - large
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
