columnSuffix: null
handle: pageBuilder
instructions: null
name: 'Page Builder'
searchable: false
settings:
  createButtonLabel: 'Add Module'
  defaultIndexViewMode: cards
  enableVersioning: false
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
