columnSuffix: null
handle: recipients
instructions: 'Enter one email address per line to notify several people.'
name: Recipients
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 3
  multiline: true
  placeholder: enquiries@example.com
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
