columnSuffix: null
handle: relatedEntries
instructions: 'Manually select the entries to display as cards. These entries are hand-picked and will not update automatically. Remember to revisit this block if selected entries are unpublished or deleted.'
name: 'Related Entries'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  defaultPlacement: end
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: 'Add Entry'
  showSearchInput: true
  showSiteMenu: false
  showUnpermittedEntries: false
  showUnpermittedSections: false
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: cards-grid
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
