columnSuffix: null
handle: replyToAddress
instructions: 'Leave blank to reply to the visitor’s own email address.'
name: 'Reply-To Address'
searchable: false
settings:
  placeholder: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Email
