columnSuffix: null
handle: showDivider
instructions: 'Toggle on to display a horizontal rule between this block and the next.'
name: 'Show Divider'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
  showLabelsInCards: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
