columnSuffix: null
handle: submitButtonLabel
instructions: 'Text shown on the submit button. Defaults to "Submit" if left blank.'
name: 'Submit Button Label'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: 'Submit'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
