columnSuffix: null
handle: subNavigation
instructions: null
name: 'Sub Navigation'
searchable: false
settings:
  createButtonLabel: 'Add Item'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - f3ef969a-f1a6-40ad-99f0-3e207a770b82 # Sub Navigation Column
        -
          - group
          - Items
    -
      __assoc__:
        -
          - uid
          - 5ef45de4-aa12-40bb-89b0-ec4b7f9f1677 # Sub Navigation Item
        -
          - group
          - Items
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
