columnSuffix: null
handle: textWidth
instructions: 'Controls the maximum width of the text column. Narrow is ideal for long-form reading. Wide suits short punchy copy or when the text sits alongside media.'
name: 'Text Width'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Narrow
        -
          - value
          - narrow
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Normal
        -
          - value
          - normal
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Wide
        -
          - value
          - wide
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
