columnSuffix: null
handle: video
instructions: null
name: Video
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - video
  branchLimit: null
  defaultPlacement: end
  defaultUploadLocationSource: 'volume:ac1caba1-2592-4da2-ae3a-0da590497fdb' # Site Assets
  defaultUploadLocationSubpath: null
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:ac1caba1-2592-4da2-ae3a-0da590497fdb' # Site Assets
  restrictedLocationSubpath: null
  selectionLabel: null
  showSearchInput: true
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:ac1caba1-2592-4da2-ae3a-0da590497fdb' # Site Assets
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Assets
