defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 92cb8c3f-4fe5-4c48-917b-4974b1323de8 # Homepage
handle: homepage
maxAuthors: 1
minAuthors: 1
name: Homepage
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  10639296-e516-422a-b738-d6027c7fa7df: # Lucidity Lab Core
    enabledByDefault: true
    hasUrls: true
    template: homepage.twig
    uriFormat: __home__
type: single
