color: null
description: null
fieldLayouts:
  67a2ee3e-af3b-4be0-9f34-c30ce3180931:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-10-24T16:57:32+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1139fcce-fbf5-411d-a668-130e00b06f48 # Accordion Title
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a770bf42-acd7-44b3-9a00-b02d8cc5ad82
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-24T16:57:32+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 9dfe14e2-5866-4d7f-92c8-59a6c28aad95 # Content
            handle: accordionContent
            instructions: null
            label: 'Accordion Content'
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: acaf3b72-cfbc-449d-af99-c25825a4f166
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-24T16:57:32+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 150eb063-4ed1-4b80-8fb8-148ecfcfa96c # Buttons
            handle: accordionButtons
            instructions: null
            label: 'Accordion Buttons'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 832b01a9-796c-41c2-b56b-d4ce2b58261e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 174ae964-f55b-48b2-a865-46b2865929f1
        userCondition: null
handle: accordionItem
hasTitleField: false
icon: list-dropdown
name: 'Accordion Item'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
