color: null
description: null
fieldLayouts:
  c2dd3738-9a3f-4988-b0f4-7950eb24d7ed:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-10-24T16:46:23+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 97413229-79db-4805-937d-9e7928582683
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-24T17:02:15+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: a52e9fd3-4d55-4e69-be7a-7e8ecf56c4db
            userCondition: null
          -
            dateAdded: '2025-10-24T16:52:26+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: bf63dd09-17a7-48ae-b1d0-f950e90d6fb5 # Heading
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c5697ea6-2589-4169-a24f-f5a4363679ba
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-24T16:52:26+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 95f73348-6bb3-48bf-a67a-d84c05fe59ec # Subheading
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c9006e1f-7191-4fc2-aadc-2c643496a8ef
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-24T16:52:26+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 9dfe14e2-5866-4d7f-92c8-59a6c28aad95 # Content
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f689e594-1cdc-41e3-b4fc-3e4196317fb3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-24T16:52:26+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 150eb063-4ed1-4b80-8fb8-148ecfcfa96c # Buttons
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f8d8e5b7-5b0a-48a9-b45e-8c9e8fbe2785
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-24T17:02:15+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 0556be71-4777-4d45-b4ff-b00aa09f585f
            userCondition: null
          -
            dateAdded: '2025-10-24T17:02:15+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e1612f48-2a9d-4807-b648-93613a63047d # Accordion Items
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f198d0e2-e86d-40f5-8a24-309a5f4dbc60
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: edcf8988-e84e-47c1-b7d2-822f3f28ca4e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-10-24T17:02:15+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3fd58a8a-1242-40a7-8a80-a53126c50fb9 # Accordion Type
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5ea499ae-cc3c-46f4-8998-a6b0630f8864
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-24T17:02:15+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: eb0ded51-07ad-483e-852f-e504254f7183 # Allow Multiple Open
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c648a2fc-8cd4-4ade-9e60-d9d92c9a1b23
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-24T17:02:15+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c4b6d510-bc29-4c46-b3b2-325b63a6b6af # First Item Open
            handle: null
            instructions: 'Open the first item on page load'
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0f5d349b-1310-42b9-a460-2da36c7b5118
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 2dbf0544-772b-4abc-b9d6-6e9e27a44e12
        userCondition: null
handle: accordion
hasTitleField: true
icon: diagram-cells
name: Accordion
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
