color: null
description: null
fieldLayouts:
  334c4b0a-f7e9-4e4c-b827-99cd1363625e:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-10-22T20:21:24+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 86c5ffd0-b34b-46e2-b14e-099e9d2e481d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-22T20:23:24+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: a4984fe5-4258-48de-9f1d-72a906c585ef
            userCondition: null
          -
            dateAdded: '2025-10-22T20:23:24+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c8188e53-9166-4ef6-87c2-a874cbe8d2b2 # Button Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 38a6893f-b7b1-4ed3-9c85-c3e75314c154
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-22T20:23:24+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a71055de-9d4a-40de-9dd1-ff9f478dc461 # Button Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 757c1163-9726-487b-8b4e-d9d98cdd2657
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6bf115d6-babc-4a29-a518-e94dfe0e0704
        userCondition: null
handle: button
hasTitleField: true
icon: null
name: Button
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
