color: null
description: null
fieldLayouts:
  a36ca7a8-f50f-4fc1-ac05-147146546cdd:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-10-22T20:59:26+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b553df29-4a23-4a96-b62c-b4a4ef1fa01e # Card Type
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ab92c4ac-9461-4399-b0e3-4ff1e73c0ee8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-22T20:59:26+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: e818bafa-d3ab-42c4-a8fa-7fe7ef966632
            userCondition: null
          -
            dateAdded: '2025-10-22T20:59:26+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: b553df29-4a23-4a96-b62c-b4a4ef1fa01e # Card Type
                  layoutElementUid: ab92c4ac-9461-4399-b0e3-4ff1e73c0ee8
                  operator: in
                  uid: 59c5dd37-c4db-465d-9e11-894443ce5475
                  values:
                    - entry
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 861f9f97-b77f-44f9-a188-b9e67b7394a2 # Entry
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 49742905-6c0c-4585-ae6e-85e6e0737d3b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-22T20:59:26+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: b553df29-4a23-4a96-b62c-b4a4ef1fa01e # Card Type
                  layoutElementUid: ab92c4ac-9461-4399-b0e3-4ff1e73c0ee8
                  operator: in
                  uid: aad09db9-a410-4898-b441-86f005f4a4a6
                  values:
                    - manual
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 09466f53-5c43-44b8-877d-70ae8f69c0ed # Card Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 60483305-51d8-4791-810f-4f2817ad3ea0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-22T20:59:26+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 3db3c40b-9d35-499b-a6d9-c008820c2015
            userCondition: null
          -
            dateAdded: '2025-10-22T21:03:46+00:00'
            dismissible: false
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: b553df29-4a23-4a96-b62c-b4a4ef1fa01e # Card Type
                  layoutElementUid: ab92c4ac-9461-4399-b0e3-4ff1e73c0ee8
                  operator: in
                  uid: 6b54533f-efe0-462f-afae-92b3ddfffade
                  values:
                    - entry
              elementType: craft\elements\Entry
              fieldContext: global
            style: tip
            tip: 'The settings below can be used to override the defaults set on the entry'
            type: craft\fieldlayoutelements\Tip
            uid: f6245601-c836-4d8d-9707-7ef6be26cf2a
            userCondition: null
          -
            dateAdded: '2025-10-22T21:03:46+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c4fba5d5-6480-4b26-b3c2-850a8ef719d7 # Card Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6b4ac125-acda-4c72-b5f8-720e167cad04
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-22T20:59:26+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: af1273d1-2c10-4bee-b314-d9cc42ebba11 # Card Summary
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 635550ff-d94d-4971-b47f-c8d940c237ee
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-22T21:07:32+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ba8d269c-876e-456d-be7b-4ac668a0703b # Card Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0c7be73d-0e6f-4830-a7c4-3c343ba8b14c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-22T20:59:26+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f81e639e-60fb-4175-a1e2-1649798a0da4 # Card CTA Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f37d9b22-2bc0-4c8a-859e-6e4b0d597580
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 31c14504-54c1-4058-934d-e522b6d270a1
        userCondition: null
handle: card
hasTitleField: false
icon: cards-blank
name: Card
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
