allowLineBreaksInTitles: false
color: null
description: 'A select menu of predefined options. Best when there are more than about five choices.'
fieldLayouts:
  75d3c7aa-4cfe-4c21-b3b1-c1bc2eb9f49f:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-08-05T00:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 5d72b7de-9907-47ef-bb23-92eed8c6d75e # Label
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9e4f2662-5f1c-4ef6-b872-7473803046c0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-08-05T00:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: e31e4468-e55c-4440-9c0a-fe97fde9f36f # Handle
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 93561fbf-13d1-4536-9870-723d99df15f3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-08-05T00:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 5b45a2a1-992c-4c9c-a38c-a86ab115d247 # Options
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 96f703c7-e0ee-41f0-9a4d-4d5b4e80dd94
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-08-05T00:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 4a3fdc4c-a7d5-4910-a28a-6e236090cc3a # AllowMultiple
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d253b615-ea46-4120-988c-364e77460d80
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-08-05T00:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: cf9416b2-b259-4aab-b078-3d7975e8032c # Width
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b6c1be05-7d73-4db2-8507-35733b911601
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-08-05T00:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 079544bf-cd35-4f05-8095-761cb8c3a1a4 # Instructions
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 92cc3116-5335-4068-ad63-d1a739c13765
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-08-05T00:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: cf7cd10a-b1d8-4a21-8ba1-ee479aefa102 # Required
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a68885b7-2cf1-4c2f-8240-73318c20da1e
            userCondition: null
            warning: null
            width: 100
        name: Field
        uid: fd8a3b38-e0a8-4b8d-9cb9-76f5337a0dfb
        userCondition: null
    thumbFieldKey: null
handle: formFieldDropdown
hasTitleField: false
icon: null
name: 'Dropdown Field'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{formFieldLabel}'
