allowLineBreaksInTitles: false
color: null
description: 'A set of options where several can be chosen at once.'
fieldLayouts:
  77e16096-aca2-46a8-9af8-6fbb2dc91795:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-08-05T00:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 5d72b7de-9907-47ef-bb23-92eed8c6d75e # Label
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f5c58fe3-0aca-4233-bdb8-34ba3c67e334
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-08-05T00:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: e31e4468-e55c-4440-9c0a-fe97fde9f36f # Handle
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5951bb8f-7c09-4380-85ee-2c02b26efa60
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-08-05T00:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 5b45a2a1-992c-4c9c-a38c-a86ab115d247 # Options
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6a026828-aa76-40a1-98ee-471c6adcaeaa
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-08-05T00:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: cf9416b2-b259-4aab-b078-3d7975e8032c # Field Width
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a08a10c0-90e3-4c68-97f1-42e9d8c1d043
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-08-05T00:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: cf7cd10a-b1d8-4a21-8ba1-ee479aefa102 # Required
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 691b6c90-cbed-4c3f-9ee8-1d4a6c79c5a1
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-08-05T00:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 079544bf-cd35-4f05-8095-761cb8c3a1a4 # Instructions
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2c7e0a24-5b8a-4370-99db-2d069323cfad
            userCondition: null
            warning: null
            width: 100
        name: Field
        uid: 8809ce93-bcdc-4cdc-83c0-fac164d98f75
        userCondition: null
    thumbFieldKey: null
handle: formFieldCheckbox
hasTitleField: false
icon: null
name: 'Checkboxes Field'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{formFieldLabel}'
