allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  0a527657-37ee-4743-93d3-c6fe9e769082:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-08-05T00:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 5d72b7de-9907-47ef-bb23-92eed8c6d75e # Label
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c723ebbb-e671-4f02-b266-5804bdb4f467
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-08-05T00:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: e31e4468-e55c-4440-9c0a-fe97fde9f36f # Handle
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3d015f45-d12d-4f72-abe4-2a490f3502d0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-08-05T00:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: b515344c-0270-4481-9cbe-6c99bc627e3e # Rows
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 537180c4-2ee2-4499-a884-353366b2f27a
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-08-05T00:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: cf9416b2-b259-4aab-b078-3d7975e8032c # Field Width
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3fb8200a-027f-4dcc-9110-57e327d5bb98
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-08-05T00:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 658185d5-c09a-4ab9-86e8-91740aac1f19 # Placeholder
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e13f7a75-c4f0-4921-a221-47dd74dd230c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-08-05T00:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 079544bf-cd35-4f05-8095-761cb8c3a1a4 # Instructions
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5e5b93ef-a46c-45ca-a2eb-8af223060668
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-08-05T00:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 38857f12-5f9f-4ff7-9095-6a8218622464 # Maximum Length
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 99125815-2e3f-402d-b7c1-41e200af1a88
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-08-05T00:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: cf7cd10a-b1d8-4a21-8ba1-ee479aefa102 # Required
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5bd9aef0-e8f5-45b4-b756-18743e0eec19
            userCondition: null
            warning: null
            width: 50
        name: Field
        uid: def62849-de31-444a-be57-67bd91c849da
        userCondition: null
    thumbFieldKey: null
handle: formFieldTextarea
hasTitleField: false
icon: null
name: 'Textarea Field'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{formFieldLabel}'
