allowLineBreaksInTitles: false
color: null
description: 'Lets the visitor attach a file. Restrict the permitted types and size — only accept uploads you genuinely need.'
fieldLayouts:
  5be945cb-96f4-4ba7-87b8-89de05cdb4eb:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-08-05T00:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 5d72b7de-9907-47ef-bb23-92eed8c6d75e # Label
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ef6a87d2-bb19-4aad-8807-edce963f8d7d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-08-05T00:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: e31e4468-e55c-4440-9c0a-fe97fde9f36f # Handle
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ede3dc13-be51-4ae8-9e4b-01e2ef657e4a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-08-05T00:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 76c6f107-b21b-42c5-a3e8-f26e518da82b # Allowed File Types
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dcbb98eb-b4ca-4c28-8d5b-1eca3edcb4ee
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-08-05T00:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: bf37e612-4f4c-4cb7-93e7-69e5cb299257 # Maximum File Size
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6cc15136-e431-4811-a4d7-657d561d79cf
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-08-05T00:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 079544bf-cd35-4f05-8095-761cb8c3a1a4 # Instructions
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 533adc3c-ba1d-42e1-8cfd-db80cc523701
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-08-05T00:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: cf7cd10a-b1d8-4a21-8ba1-ee479aefa102 # Required
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2840e59f-8a1b-485c-9240-56c3d6fc9c64
            userCondition: null
            warning: null
            width: 100
        name: Field
        uid: 3f14b73a-9f78-4461-a3b4-a7aa055352d9
        userCondition: null
    thumbFieldKey: null
handle: formFieldFile
hasTitleField: false
icon: null
name: 'File Upload Field'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{formFieldLabel}'
