allowLineBreaksInTitles: false
color: null
description: 'A single-line text input. Use the input type setting to switch it to an email, telephone, number, URL or date input.'
fieldLayouts:
  d5c794fe-5044-47c9-9eb6-29450a85b335:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-08-05T00:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 5d72b7de-9907-47ef-bb23-92eed8c6d75e # Label
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 12d1d530-19b6-480f-ab08-510d4e72f5b7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-08-05T00:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: e31e4468-e55c-4440-9c0a-fe97fde9f36f # Handle
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6618858f-b3ee-4b27-946a-852987b6f6df
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-08-05T00:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 04b5630b-27b2-41ae-ba8a-3e428cacd36d # InputType
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e9436026-1ed4-4a28-ad08-db363077424b
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-08-05T00:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: cf9416b2-b259-4aab-b078-3d7975e8032c # Width
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 83150ed6-c973-4a50-aade-0ac223b17fa4
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-08-05T00:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 658185d5-c09a-4ab9-86e8-91740aac1f19 # Placeholder
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5dbd9522-5240-4938-a681-a59e1c8767a5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-08-05T00:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 079544bf-cd35-4f05-8095-761cb8c3a1a4 # Instructions
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 928af71f-4bce-4b24-811b-c36b4a6a66fd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-08-05T00:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 38857f12-5f9f-4ff7-9095-6a8218622464 # MaxLength
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ceac5d59-c373-4ec0-915b-5a033e9a7773
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-08-05T00:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: cf7cd10a-b1d8-4a21-8ba1-ee479aefa102 # Required
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f8f0f835-89bb-4cba-aa3c-d992c8813d38
            userCondition: null
            warning: null
            width: 50
        name: Field
        uid: ca870235-2f45-424f-a988-ed2c7f31705d
        userCondition: null
    thumbFieldKey: null
handle: formFieldText
hasTitleField: false
icon: null
name: 'Text Field'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{formFieldLabel}'
