color: null
description: null
fieldLayouts:
  46b3c4f8-aed2-42bf-b441-78aee8de8143:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-10-22T20:44:54+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 77cd2efa-1e2b-456b-aacc-726a023855f8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-22T20:48:47+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 120265e9-8f4f-446f-a982-375d9dc01ad7
            userCondition: null
          -
            dateAdded: '2025-10-22T20:48:47+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: bf63dd09-17a7-48ae-b1d0-f950e90d6fb5 # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2ba5b361-9211-4e4c-854b-c42d25d94bc4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-22T20:48:47+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 95f73348-6bb3-48bf-a67a-d84c05fe59ec # Subheading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 822b737d-879a-4641-a4ae-91ea89134676
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-22T20:48:47+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 9dfe14e2-5866-4d7f-92c8-59a6c28aad95 # Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 321aa5bd-039b-49d1-8a48-8c33bb380fe2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-22T20:48:47+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 150eb063-4ed1-4b80-8fb8-148ecfcfa96c # Buttons
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: daad964f-702a-42ce-8608-5a936a1fab58
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d5fca4eb-10ce-464c-b791-3a5ec4f6b68b
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-10-22T20:48:47+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 513c0726-c6a0-46e6-8ccf-6963b6211909 # Media Type
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 539b73f3-c104-4e8b-b470-c5a1f13956fc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-22T20:48:47+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 0a4732a1-14f7-4980-a77b-2ce38c726fc0
            userCondition: null
          -
            dateAdded: '2025-10-22T20:48:47+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: 513c0726-c6a0-46e6-8ccf-6963b6211909 # Media Type
                  layoutElementUid: 539b73f3-c104-4e8b-b470-c5a1f13956fc
                  operator: in
                  uid: 6b5ef5df-fc79-4d69-b1ae-a6fa8bcde748
                  values:
                    - image
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 608dee82-9418-4235-a9c0-53a817c2cacc # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a7c40168-5989-4a87-b275-086ba8723e3b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-22T20:48:47+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: 513c0726-c6a0-46e6-8ccf-6963b6211909 # Media Type
                  layoutElementUid: 539b73f3-c104-4e8b-b470-c5a1f13956fc
                  operator: in
                  uid: d3457f2c-695e-4be1-ab0f-9a011f1603d5
                  values:
                    - video
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 53bbcd4a-9def-4156-9e68-6c7f8019c7fa # Video
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 383937bf-0b5f-455c-8a45-a65095cb356d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-22T20:48:47+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: 513c0726-c6a0-46e6-8ccf-6963b6211909 # Media Type
                  layoutElementUid: 539b73f3-c104-4e8b-b470-c5a1f13956fc
                  operator: in
                  uid: 97676fb7-8b2d-46cd-89a3-74e89cbebe75
                  values:
                    - video
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 608dee82-9418-4235-a9c0-53a817c2cacc # Image
            handle: videoPlaceholder
            includeInCards: false
            instructions: null
            label: 'Video Placeholder'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 79521a5b-308c-40f4-9a3d-46e57b8e2618
            userCondition: null
            warning: null
            width: 100
        name: Media
        uid: b69acd49-8d55-47c1-a4b1-c7db92a14ae1
        userCondition: null
handle: fullWidthMedia
hasTitleField: true
icon: image
name: 'Full Width Media'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
