allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  8f5984da-3c51-4dd2-9691-0503f573227e:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-10-22T20:17:23+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 05f179a6-d8e4-47d0-9fe9-c63c802d0f4d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-22T20:23:50+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: d5047276-8a0f-40df-9d23-8518ecc729ad
            userCondition: null
          -
            dateAdded: '2025-10-22T20:23:50+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: bf63dd09-17a7-48ae-b1d0-f950e90d6fb5 # Heading
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c774b80e-a8fb-4132-8d02-f0ff24448ea0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-22T20:23:50+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 95f73348-6bb3-48bf-a67a-d84c05fe59ec # Subheading
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 086f2c14-6285-4f6d-a956-2c094c762a9a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-22T20:23:50+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 9dfe14e2-5866-4d7f-92c8-59a6c28aad95 # Content
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d185a451-bec7-46b8-8cb1-c11328081ede
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-22T20:23:50+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 150eb063-4ed1-4b80-8fb8-148ecfcfa96c # Buttons
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5c01dc91-d586-437f-b425-68640fdcc917
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 85fe1279-3dee-4299-8ead-f0297f7fc2ed
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-10-22T20:27:41+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 513c0726-c6a0-46e6-8ccf-6963b6211909 # Media Type
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a5b0727e-626a-47e4-ad6a-b6d8958d6ce3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-22T20:27:41+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 138d4e25-dddc-41ce-917d-7ff87f036ec7
            userCondition: null
          -
            dateAdded: '2026-04-21T20:11:40+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: 513c0726-c6a0-46e6-8ccf-6963b6211909 # Media Type
                  layoutElementUid: a5b0727e-626a-47e4-ad6a-b6d8958d6ce3
                  operator: in
                  uid: d4281023-4e9e-4ceb-9b90-b72c986d7c13
                  values:
                    - image
              elementType: craft\elements\Entry
              fieldContext: global
            elementEditCondition: null
            fieldUid: 608dee82-9418-4235-a9c0-53a817c2cacc # Image
            handle: null
            instructions: null
            label: 'Hero Image'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b2d3e020-b5f3-4e62-a0dd-fb3464c25705
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-21T20:11:40+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: 513c0726-c6a0-46e6-8ccf-6963b6211909 # Media Type
                  layoutElementUid: a5b0727e-626a-47e4-ad6a-b6d8958d6ce3
                  operator: in
                  uid: 01406bb3-18ea-490b-827e-74f9bb7cc0c8
                  values:
                    - video
              elementType: craft\elements\Entry
              fieldContext: global
            elementEditCondition: null
            fieldUid: 53bbcd4a-9def-4156-9e68-6c7f8019c7fa # Video
            handle: null
            instructions: null
            label: 'Hero Video'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b1caec8e-1c8f-41f3-ba6c-c39dcf4ac2fb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-22T20:27:41+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: 513c0726-c6a0-46e6-8ccf-6963b6211909 # Media Type
                  layoutElementUid: a5b0727e-626a-47e4-ad6a-b6d8958d6ce3
                  operator: in
                  uid: 3f698d26-7035-45f3-a84b-79964c72158c
                  values:
                    - video
              elementType: craft\elements\Entry
              fieldContext: global
            elementEditCondition: null
            fieldUid: d8197259-a569-4a9e-a1c0-61a702caaccb # Background Image
            handle: videoPlaceholder
            instructions: null
            label: 'Video Placeholder'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ad5a5478-3405-45a7-b314-b8fada241624
            userCondition: null
            warning: null
            width: 100
        name: Media
        uid: dc4bd50a-e399-4187-ae6f-0cdfa593d719
        userCondition: null
    thumbFieldKey: null
handle: homepageHero
hasTitleField: true
icon: house-chimney-heart
name: 'Homepage Hero'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
