color: null
description: null
fieldLayouts:
  2b409297-a1d6-4bac-97d1-285b40e8a004:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-10-25T20:56:03+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: 'Item Label'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9dce6f84-957f-446f-a669-270a24c5c294
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-25T21:25:05+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 001e0cd3-39f5-451f-918d-1a6654aee7e5 # Item Link
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1f8fb6a3-7cfe-47ff-8be1-6866fe957b9c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-25T21:25:05+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7df558db-d939-4096-8a38-33326dc5a62c # Show Dropdown
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6f12f545-c733-4c83-9fc6-b96bf30f376c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 285abcdc-15c2-402f-879b-fa1de8c10ac6
        userCondition: null
      -
        elementCondition:
          class: craft\elements\conditions\entries\EntryCondition
          conditionRules:
            -
              class: craft\fields\conditions\LightswitchFieldConditionRule
              fieldUid: 7df558db-d939-4096-8a38-33326dc5a62c # Show Dropdown
              layoutElementUid: 6f12f545-c733-4c83-9fc6-b96bf30f376c
              uid: b2607eb9-c922-4813-8a73-47435a969d63
              value: true
          elementType: craft\elements\Entry
          fieldContext: global
        elements:
          -
            dateAdded: '2025-10-25T21:49:15+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: aa68fe4c-1fc8-4dc7-ad17-aa8e75b573eb # Sub Navigation
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a4b8e153-9a10-4e9c-ad3e-5ec255b153da
            userCondition: null
            warning: null
            width: 100
        name: 'Sub Navigation'
        uid: d7f918b8-1a49-4838-83e0-e16c05076117
        userCondition: null
handle: navigationItem
hasTitleField: true
icon: null
name: 'Navigation Item'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
