allowLineBreaksInTitles: false
color: null
description: "Add a block of formatted text content. Use this for standalone body copy, introductory paragraphs, or any text that doesn't require accompanying media. Supports headings, lists, links, and inline formatting."
fieldLayouts:
  50e8e442-c851-4b02-a9be-fc0e557e498a:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-05-08T18:08:29+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 0f9b9e17-101f-4872-b379-0580759feb60 # Heading
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e84f7214-7b0f-4b08-a3cb-c50e251e24fd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-08T18:08:29+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 71e33e54-78fb-4f11-b849-99b5049f05c1 # Subheading
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 48c9cb88-c0fa-44e4-bb5d-c3a46b563384
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-08T18:08:29+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 09ce0edf-8e53-41b3-8bba-638137be0807 # Body Text
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7f942f15-8a43-480d-86a9-8a09e412122d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-08T18:21:44+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 109e517e-9dc3-4f28-af6d-0c58ce9f09fb # Buttons
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 49171e06-c7de-4e17-b6b3-1b2724fc258d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9081b9f0-c477-4f8d-8e44-4c913c522e8f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-05-08T18:08:29+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 2676374e-3103-4010-b9db-7133d8ecd83a # Text Width
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 41fbbc1e-09b4-41d5-bcc0-a5736c890a80
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-08T18:08:29+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 1bf9dab4-7e13-4c52-9413-1699e784a61f # Text Alignment
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9cd50aad-2727-4ba9-8b6d-6b100aea0751
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-08T18:08:29+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: bf028855-6a25-45f5-a354-72a84db39f97 # Background Colour
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2386a040-de4b-4545-8aff-9d8a5133df7d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-08T18:08:29+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 7fd5fa17-7ae3-4e95-93d4-718424631e95 # Padding Size
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8d92745b-d176-413b-9d34-dfd2eb3836cb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-08T18:08:29+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 832307e6-5881-4c7f-9c1d-6cea16f9108f # Anchor ID
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 31097e31-ec4c-4e7d-9eb9-1cdaddadb80f
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 28a604b9-800b-43e4-8802-68a1046ad098
        userCondition: null
    thumbFieldKey: null
handle: richText
hasTitleField: false
icon: null
name: 'Rich Text'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: 'Rich Text - {heading.text}'
